[package]
authors = ["Hendrik Sollich <hendrik@hoodie.de>"]
name = "web"
version = "0.1.0"

[dependencies]
env_logger = "*"
iron = "*"
json = "*"
log = "*"
mount = "*"
params = "*"
router = "*"
staticfile = "*"
